### ISSUE TITLE
Migration handler not found for entry My eModul for tech

### ISSUE THREAD

**Issue by Roger954** [mariusz-ostoja-swierczynski/tech-controllers#93]
### The problem

Since update to core 2024.6.x, the eModul integration does not work anymore. 

### What version of Tech Controllers integration has the issue?

2.3.1

### What version of Home Assistant Core has the issue?

2024.6.2

### Anything in the logs that might be useful for us?

```txt
ERROR (MainThread) [homeassistant.config_entries] Migration handler not found for entry My eModul for tech
```

**Comment by anarion80** [comment]
@Roger954 I just did a test on HA version 2024.5.4, installed tech controllers v.2.3.1, setup up all the 4 controllers from test account and then upgraded HA to 2024.6.2. 
There was no error, everything is working fine as it should. Are you sure you were using the latest tech controllers version? Migrations were removed in 2.3.1 and we said in release notes to remove the integration at that point and then add again.

So please provide more info and more logs, otherwise we can't proceed.

**Comment by Roger954** [comment]
Hi,

Thanks for the reply. I'm very sure that I'm using v2.3.1 and all other latest releases of HA and HACS. Not sure what other logs you'd like to have, please do let me know which ones (and possbily how).

All I can find is 'ERROR (MainThread) [homeassistant.config_entries] Migration handler not found for entry My eModul for tech' in configuration.yaml and this one in the Home Assistant Core logs:

---
Logger: homeassistant.config_entries
Source: config_entries.py:919
First occurred: 16:02:10 (1 occurrences)
Last logged: 16:02:10

Migration handler not found for entry My eModul for tech
---

Thanks

**Comment by Roger954** [comment]
The issue is fixed!!! I deleted the hub and re-added it again, that solved it!
Should have tried that earlier, sorry about that..

Thanks

**Comment by anarion80** [comment]
Ok, thanks. I will close the issue then.
